// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6N14PcyQpgx_d6_leI5r7lCZ85Bf-v8',
    appId: '1:636653464866:web:4edab2b7ea5a5b4ea5897b',
    messagingSenderId: '636653464866',
    projectId: 'friendchat-e62e7',
    authDomain: 'friendchat-e62e7.firebaseapp.com',
    storageBucket: 'friendchat-e62e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLbJYTaUCqD5Mhv6ngpkyfVtYO-SHag6o',
    appId: '1:636653464866:android:f4bf25525bb52c80a5897b',
    messagingSenderId: '636653464866',
    projectId: 'friendchat-e62e7',
    storageBucket: 'friendchat-e62e7.firebasestorage.app',
    databaseURL: 'https://console.firebase.google.com/u/0/project/friendchat-e62e7/firestore/databases/enockdev'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbnyRhAQ1ezsd0hOfVGncSoBH1PmqyoU',
    appId: '1:636653464866:ios:0340d3e0db3e471aa5897b',
    messagingSenderId: '636653464866',
    projectId: 'friendchat-e62e7',
    storageBucket: 'friendchat-e62e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://console.firebase.google.com/u/0/project/friendchat-e62e7/firestore/databases/enockdev'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABbnyRhAQ1ezsd0hOfVGncSoBH1PmqyoU',
    appId: '1:636653464866:ios:0340d3e0db3e471aa5897b',
    messagingSenderId: '636653464866',
    projectId: 'friendchat-e62e7',
    storageBucket: 'friendchat-e62e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6N14PcyQpgx_d6_leI5r7lCZ85Bf-v8',
    appId: '1:636653464866:web:cd3d2499019b80b4a5897b',
    messagingSenderId: '636653464866',
    projectId: 'friendchat-e62e7',
    authDomain: 'friendchat-e62e7.firebaseapp.com',
    storageBucket: 'friendchat-e62e7.firebasestorage.app',
  );
}
